name: Publish
 
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run cake
        env:
          CHOCOAPIKEY: ${{ secrets.CHOCOAPIKEY }}
        run: ./build.sh
